def OAuth2Exception(Exception):
    pass
